### PR TITLE
fixed damages

### LINKED ISSUE #88: player knock down appears to happen at -1, not -2

### PR DESCRIPTION
**Pull request by jsonlamm**
fixes #88

### CODE REVIEW

File: browser/reducers/gameState/armor.js [hunk 1]
```diff
@@ -18,8 +18,7 @@ export const damageArmor = (player, location, amount) => (
 			amount = playerArmor[location] + 2;
 		}
 		if (
-			playerArmor[location] !== -2 ||
```
Comment (waterfoul) [inline browser/reducers/gameState/armor.js:21]: This check needs to be re-added, don't merge till it's  fixed
